"""empty message

Revision ID: 58999c4738fd
Revises: 
Create Date: 2018-06-24 17:01:23.606217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58999c4738fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopify_app_reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_app_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shopify_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('app_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('star_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_star_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'shopify_app_reviews_pkey')
    )
    # ### end Alembic commands ###
