"""empty message

Revision ID: a9f11a868219
Revises: c46d64cef027
Create Date: 2018-06-27 18:12:20.404897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f11a868219'
down_revision = 'c46d64cef027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shopify_app_reviews_shopify_domain'), 'shopify_app_reviews', ['shopify_domain'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopify_app_reviews_shopify_domain'), table_name='shopify_app_reviews')
    # ### end Alembic commands ###
