"""empty message

Revision ID: c46d64cef027
Revises: 
Create Date: 2018-06-27 16:31:37.589576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46d64cef027'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_app_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_domain', sa.String(), nullable=True),
    sa.Column('app_slug', sa.String(), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('previous_star_rating', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopify_app_reviews')
    # ### end Alembic commands ###
